# Home Assistant BLE Tracker
#
#Track your BLE Devices
#
#
substitutions:
  device_name: ble-tracker
  friendly_name: BLE
  device_description: "track BLE Devices"

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '${device_name}'
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_password
  
ota:
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5
  
web_server:
  port: 80
  auth:
    username: !secret esphome_web_username
    password: !secret esphome_web_password
    
# Sensors for ESP version and WIFI information
text_sensor:
  - platform: version
    hide_timestamp: true
    name: "${friendly_name} - ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} - IP Address"
      icon: mdi:wifi
    ssid:
      name: "${friendly_name} - Connected SSID"
      icon: mdi:wifi-strength-2

#BLE Tracker
esp32_ble_tracker:
  scan_parameters:
   interval: 30ms
   duration: 30s

binary_sensor:
  - platform: ble_presence
    mac_address: XXXXXXX
    device_class: presence
    icon: mdi:face-man-outline
    name: "XXXX"
  - platform: ble_presence
    mac_address: XXXXXX
    device_class: presence
    icon: mdi:face-profile-woman
    name: "XXXXXX"

sensor:
  - platform: ble_rssi
    mac_address: XXXXXX
    name: "XXXXXX"
    filters:
      heartbeat: 5s
  - platform: ble_rssi
    mac_address: XXXXXX
    name: "XXXXXX"
    filters:
      heartbeat: 5s


    
